apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${ACCOUNT_ID}:role/product-catalog-fe-commercial-staging-role
  name: product-catalog-fe-sa
  namespace: product-catalog-fe
