apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: app-name
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: branch-name
  secretRef:
    name: app-name
  timeout: 60s
  url: ssh://git@github.com/phrankson/app-name-manifests

